### ISSUE TITLE
Must add JSON on bad image to submit

### ISSUE THREAD

**Issue by afriestad** [tims-j/corridors-of-time#3]
https://github.com/Corridors-of-Time-Transcription/corridors-of-time/blob/4f3ac6b4f56df513ca0ced094f2511effbac0791/pages/transcribe.js#L153

This line should probably also check whether the image is marked as bad, and if so not require JSON to be filled in. The JSON is overwritten in the backend anyhow.

Reported by user in Discord: https://discordapp.com/channels/667254133589540874/667602037302624266/668503135735513089

**Comment by jorgev259** [comment]
https://github.com/Corridors-of-Time-Transcription/corridors-of-time/pull/6

**Comment by tims-j** [comment]
@afriestad There is planned work to add a seperate report button so that users don't have to submit request data at all in the case of a bad image.

Just waiting on some backend work in order to enable this feature.

**Comment by tims-j** [comment]
This has now been fixed in this release: https://github.com/Corridors-of-Time-Transcription/corridors-of-time/commit/53cb8a16e6b864eaa352861f0881dbdef5d1cea2
